image:
  repository: "registry.digitalocean.com/guajiro/landing-static"
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

#
# If your cluster needs a pull secret, set it here (example):
# imagePullSecrets:
#   - name: do-registry
#

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "demo.guajiro.xyz"
  hosts:
    - demo.guajiro.xyz
  tls:
    - secretName: landing-tls
      hosts:
        - demo.guajiro.xyz
