apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:julio-at/argocd-landing.git"
    targetRevision: HEAD
    path: helm/landing
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
